### ISSUE TITLE
Speed up tests on travis

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#353]
**Objective:** Reduce test latency and speed up our development workflow.

As of June 1 2017, test currently take about 2.5hrs to run on travis. More than half of that time is wasted by running tests that are muted by the `try(test_that())` idiom (see #395). E.g. we currently spend ~28 minutes running `test-mcmc.R` and then ignore all errors (there are three errors, see #404).

**Tasks:**
- [x] #352 Profile test-devel.sh tests
- [x] #352 Prioritize test-devel.sh tests by duration (and maybe probability of failure)
- [x] #393 Switch to container infrastructure and `cache: packages`
- [x] #439 Parallelize tests on travis.
- [x] #450 Create a parallelized runner for faster local testing (run one test file per core)

**Comment by perrydv** [comment]
The slowest tests are ones that run MCMC, MCEM, or exhaustively test models.  At least for the first two, there are multiple goals all wrapped together currently: statistical validation that a posterior sample is reasonable, and algorithm validation that exactly the same chain is generated in compiled and uncompiled mode and matches what we've generated before.   We could make fast versions of MCMC and MCEM where we use something ridiculous like 5 samples just for the second purpose and relegate the first purpose to the longer/slower test suite.  The test-mcmc tests are valuable because they contain the most diversity of "real" nimbleFunctions as well as some diversity of models not all represented (I don't think) in test-models.

**Comment by fritzo** [comment]
@perrydv I like the idea of testing with just 5 samples.

For reference, here is the profiled set of tests (just pasted from the now automatically prioritized [test-devel.sh](https://github.com/nimble-dev/nimble/blob/profile-tests/test-devel.sh#L6)):
```
$RUNNER packages/nimble/inst/tests/test-types.R  # takes 0.94 seconds
$RUNNER packages/nimble/inst/tests/test-checkDSL.R  # takes 1.78 seconds
$RUNNER packages/nimble/inst/tests/test-misc.R  # takes 1.89 seconds
$RUNNER packages/nimble/inst/tests/test-setData.R  # takes 2.2 seconds
$RUNNER packages/nimble/inst/tests/test-getDependencies.R  # takes 3.87 seconds
$RUNNER packages/nimble/inst/tests/test-errors.R  # takes 4.03 seconds
$RUNNER packages/nimble/inst/tests/test-modelValuesInterface.R  # takes 5.33 seconds
$RUNNER packages/nimble/inst/tests/test-optim.R  # takes 9.52 seconds
$RUNNER packages/nimble/inst/tests/test-nimbleFunctionInterfaces.R  # takes 11.08 seconds
$RUNNER packages/nimble/inst/tests/test-dsl_dists.R  # takes 13.25 seconds
$RUNNER packages/nimble/inst/tests/test-getDistributionInfo.R  # takes 14.15 seconds
$RUNNER packages/nimble/inst/tests/test-size.R  # takes 35.44 seconds
$RUNNER packages/nimble/inst/tests/test-declare.R  # takes 44.82 seconds
$RUNNER packages/nimble/inst/tests/test-nimbleList_RCfun.R  # takes 53.15 seconds
$RUNNER packages/nimble/inst/tests/test-mcem.R  # takes 65.57 seconds
$RUNNER packages/nimble/inst/tests/test-getBound.R  # takes 88.2 seconds
$RUNNER packages/nimble/inst/tests/test-compareMCMCs.R  # takes 101.4 seconds
$RUNNER packages/nimble/inst/tests/test-distributions.R  # takes 119 seconds
$RUNNER packages/nimble/inst/tests/test-nimbleList.R  # takes 128.91 seconds
$RUNNER packages/nimble/inst/tests/test-user.R  # takes 134.32 seconds
$RUNNER packages/nimble/inst/tests/test-allocation.R  # takes 200.52 seconds
$RUNNER packages/nimble/inst/tests/test-math.R  # takes 217.93 seconds
$RUNNER packages/nimble/inst/tests/test-coreR.R  # takes 273.36 seconds
$RUNNER packages/nimble/inst/tests/test-getParam.R  # takes 278.14 seconds
$RUNNER packages/nimble/inst/tests/test-copy.R  # takes 521.16 seconds
$RUNNER packages/nimble/inst/tests/test-filtering.R  # takes 565.14 seconds
$RUNNER packages/nimble/inst/tests/test-trunc.R  # takes 579.12 seconds
$RUNNER packages/nimble/inst/tests/test-models.R  # takes 594.9 seconds
$RUNNER packages/nimble/inst/tests/test-numericTypes.R  # takes 1220.14 seconds
$RUNNER packages/nimble/inst/tests/test-mcmc.R  # takes 1684.73 seconds
```

**Comment by paciorek** [comment]
Fritz, it turns out we already have a flag for test_mcmc() that allows turning off the slow process of resampling data and then running long MCMC chains and checking frequentist coverage. Simply set 'resampleData = FALSE'.

**Comment by fritzo** [comment]
Chris, I tried setting `resampleData = FALSE`, but tests still seemed slow.

**Comment by paciorek** [comment]
There's a bunch of compilation and for each MCMC we generate 5-10 samples
using the R MCMC. This can be very slow so that might be why. One option
would be to choose a careful subset of the BUGS models to test, based on
the kinds of model structure present so that we hit different parts of the
MCMC codebase.

**Comment by perrydv** [comment]
@paciorek the test-mcmc has been updated on branch modernize-test-mcmc (a series of similar branches.  Will go over it with you soon.  It does not address the speed, but does manage the known errors differently and automates generation of log files and comparison of any changes in logged output.

**Comment by fritzo** [comment]
Closing this for now, since parallelizing has helped.
