### ISSUE TITLE
Compile all of buildMCEM

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#372]
Currently `buildMCEM` is prevented from being compiled due to its use of `optim()`. As of #367 , `optim()` should have enough functionality to unblock compilation of `buildMCEM`. The [MCEM_nimbleFunction](https://github.com/nimble-dev/nimble/compare/MCEM_nimbleFunction) branch does some of the cleanup work to get the rest of `buildMCEM` to compile.

### Tasks:
- [ ] Merge #367
- [ ] Avoid setting `names()` of output types (or define a custom `nimbleList` type for output)
- [ ] Avoid unsupported error checking (e.g. `is.numeric()`)
- [ ] Clean up non-compilable functions in `buildMCEM$estimateCov`.

**Comment by paciorek** [comment]
Moving to nimbleCoreTeam.
