### ISSUE TITLE
Fix any transpose issues with Tensorflow linear algebra

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#586]
## Tasks

- [ ] Create test utilities like `test_math()`/`mathTestLists.R` but that make it easier to test with a variety of matrices with various constraints (symmetry, positive definiteness, NANs on the strict lower diagonal, etc.).
- [ ] Fix `forwardsolve()`, which may have a transpose bug.
- [ ] Fix `backsolve()`, which may have a transpose bug.
- [ ] Fix `chol()`, which apparently fills only the upper triangle (what is the desired behavior?).

These functions currently marked TODO in their definitions in [`tfTranslate()`](https://github.com/nimble-dev/nimble/blob/bef314bf5aea5d825cfdf2b2679afaa9248c03be/packages/nimble/R/genCpp_TFize.R#L159). Some are marked `xfail` in [`mathTestLists.R`](https://github.com/nimble-dev/nimble/blob/devel/packages/nimble/inst/tests/mathTestLists.R).

## Transpose nuances

When Nimble uses the tensorflow back-end, matrices are passed by reference to avoid copying. Since R is column-major and Tensorflow is row-major, Nimble treats each matrix as transposed when it appears in an a tensorflow expression. For example Nimble compiles the R expression `x %*% y` to the tensorflow expression `tf$matmul(y, x)`. Similarly, Nimble compiles the R `chol(x)` (which reads the column-major-upper-triangle of `x`) to `tf$cholesky(x)` (which reads the row-major-lower-triangle of `x`).

See also the discussion of `chol()` in #584

**Comment by paciorek** [comment]
Moving to nimbleCoreTeam given experimental nature of TF support.
